name: testcafe-commonjs
'on':
  push: null
  schedule:
    - cron: 0 5 2-31/2 * *
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm install'
        run: npm install -g testcafe
      - name: 'npm:install'
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: build
        run: npm run build --if-present
      - name: test
        uses: DevExpress/testcafe-action@latest
        with:
          args: chrome:headless spec/*.spec.js
